# Лабораторна робота "Операції над масивами NumPy"

__Метою__ лабораторної роботи є набуття практичних навичок та закріплення теоретичних знань по обробці великих однорідних наборів даних які розташовані у вигляді масивів бібліотеки __NumPy__.

Виконати послідовно завдання в секціях, попередню засвоївши наведені приклади
В завданнях продовжити написання коду замість `...`. 

__Імена змінних в завданнях змінювати не можна!__

### Предвстановлення

In [1]:
# Імпортувати бібліотеку numpy з аліасом np
import numpy as np

In [2]:
# Вивід таблиці відповідності кодів типів даних в NumPy
import pandas as pd
dtypes = pd.DataFrame(
    {
        'Type': ['int8', 'uint8', 'int16', 'uint16', 'int32', 'uint32', 'int64', 'uint64', 'float16', 'float32', 'float64', 'float128', 'complex64', 'complex128', 'bool', 'object', 'string_', 'unicode_'],
        'Type Code': ['i1', 'u1', 'i2', 'u2', 'i4', 'u4', 'i8', 'u8', 'f2', 'f4 or f', 'f8 or d', 'f16 or g', 'c8', 'c16', '', 'O', 'S', 'U']
    }
)

dtypes

Type Type Code
0         int8        i1
1        uint8        u1
2        int16        i2
3       uint16        u2
4        int32        i4
5       uint32        u4
6        int64        i8
7       uint64        u8
8      float16        f2
9      float32   f4 or f
10     float64   f8 or d
11    float128  f16 or g
12   complex64        c8
13  complex128       c16
14        bool          
15      object         O
16     string_         S
17    unicode_         U

## 1. Створення та інспектування _np-массивів_

### ПРИКЛАДИ

In [3]:
# Створити 1-вимірний масив з 5 цілочисельних елементів 
arr = np.array([23, 42, 13, 7, 0])

In [4]:
# Інспектування массива
np.info(arr)

class:  ndarray
shape:  (5,)
strides:  (4,)
itemsize:  4
aligned:  True
contiguous:  True
fortran:  True
data pointer: 0x18b37f8daa0
byteorder:  little
byteswap:  False
type: int32


In [5]:
# створити 2-мірний масив з цілим типом даних у 2-х байтовому форматі
arr = np.array([[1,2,3], [4,5,6]], dtype='i2')
print(arr)

[[1 2 3]
 [4 5 6]]


In [6]:
# створити масив із  значень в інтервалі 0 - 20 з кроком 2
# np.arange(start, stop, step)
arr = np.arange(0, 20, 2)  
print(arr)

[ 0  2  4  6  8 10 12 14 16 18]


In [7]:
# створити масив із 20 рівномірно розміщених значень в інтервалі 0 - 10 
# np.linspace(start, stop, num_of_elements) 
arr = np.linspace(0, 10, 20)
print(arr)

[ 0.          0.52631579  1.05263158  1.57894737  2.10526316  2.63157895
  3.15789474  3.68421053  4.21052632  4.73684211  5.26315789  5.78947368
  6.31578947  6.84210526  7.36842105  7.89473684  8.42105263  8.94736842
  9.47368421 10.        ]


In [8]:
# створити масив 3х3 випадкових значень 
arr = np.random.rand(3, 3)
print(arr)

[[0.85256158 0.1456622  0.30399802]
 [0.75925776 0.13405958 0.43659089]
 [0.23954918 0.43957406 0.30603048]]


In [9]:
# створення нульвих, одиничних та заповнених масивів
zeros = np.zeros((2,3), dtype='i4')
print(zeros)
ones = np.ones((2,3))
print(ones)
filled = np.full((2,3), 123)
print(filled)

[[0 0 0]
 [0 0 0]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[123 123 123]
 [123 123 123]]


In [10]:
print(arr, end="\n...\n")
# інспектування типу массиву `dtype`
print(arr.dtype)
# інспектування розмірності массиву `shape`
print(arr.shape)
# інспектування довжини масиву `len`
print(len(arr))
# інспектування кількості вимірів масиву `ndim`
print(arr.ndim)
# інспектування кількості елементів в масиві `size`
print(arr.size)
# інспектування коількості байтів на елемент `itemsize`
print(arr.itemsize)
# інспектування кількості пам'яти під масив `nbytes`
print(arr.nbytes)

[[0.85256158 0.1456622  0.30399802]
 [0.75925776 0.13405958 0.43659089]
 [0.23954918 0.43957406 0.30603048]]
...
float64
(3, 3)
3
2
9
8
72


In [11]:
arr.__sizeof__()

192

### ЗАВДАННЯ 1

In [22]:
### ЗАВДАННЯ 1.1: створити та проінспектувати масив 3х4 з ім'ям arr1_1, який містить числа з плавоючою точкою 
import random
#arr1_1 = np.array([random.random() for i in range(10)]).reshape((3, 4))
arr1_1 = np.random.sample((3, 4))
print(arr1_1)
np.info(arr1_1)

[[0.48892292 0.6639419  0.25780935 0.37311569]
 [0.38103431 0.6963507  0.58000792 0.37481557]
 [0.94846057 0.4174572  0.91008286 0.26821212]]
class:  ndarray
shape:  (3, 4)
strides:  (32, 8)
itemsize:  8
aligned:  True
contiguous:  True
fortran:  False
data pointer: 0x18b380750c0
byteorder:  little
byteswap:  False
type: float64


In [23]:
### ЗАВДАННЯ 1.2: створити одномірний масив з 5 строкових елементів
arr1_2 = np.array([1, 2, 3, 4, 5])
print(arr1_2)

[1 2 3 4 5]


In [24]:
### ЗАВДАННЯ 1.3: створити одиничний масив 3х4 чисел з плаваючою точкою
arr1_3 = np.random.rand(3, 4)
print(arr1_3)

[[0.39604999 0.21190624 0.00978056 0.86615905]
 [0.78823199 0.77467273 0.37715524 0.28605096]
 [0.08742811 0.09075923 0.50088794 0.36436423]]


## 2. Перетворення форми та типу массивів

### ПРИКЛАДИ

In [25]:
# створити 2-мірний float-масив (2х5) з лінійного int-списка 
spisok = list(range(0,10))
arr = np.array(spisok)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [26]:
#преретворити форму масива `reshape` 
arr = arr.reshape((2,5))
print(arr)
print(arr.dtype)

[[0 1 2 3 4]
 [5 6 7 8 9]]
int32


In [27]:
# -- 3 перетворити тип масива `astype`
arr = arr.astype('float64')
print(arr)
print(arr.dtype)

[[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]]
float64


In [28]:
# 'вирівняти' 2-мірний масив
arr = arr.flatten()
print(arr)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


### ЗАВДАННЯ 2

In [3]:
### ЗАВДАННЯ 2.1: створити 3-мірний масив (3х1х3) логічного 'False'
arr2_1 = np.arange(9).reshape(3, 1, 3)
print(arr2_1)

[[[0 1 2]]

 [[3 4 5]]

 [[6 7 8]]]


In [4]:
### ЗАВДАННЯ 2.2: перетворити масив arr2_1 в 2-мірний масив (3х3) типу int
arr2_2 = int(arr2_1)
print(arr2_2)

TypeError: only size-1 arrays can be converted to Python scalars

In [ ]:
### ЗАВДАННЯ 2.3: створити  2-мірний масив парних чисел в інтервалі 10-21
arr2_3 = ...
...
print(arr2_3)

## 3. Доступ до  елементів масива

### ПРИКЛАДИ

In [5]:
arr = np.array([10, 6, 7, 21, 44]) 
print(arr)

# 1-й елемент 
print(arr[0])
# 3-й елемент
print(arr[2])
# останній елемент
print(arr[-1])

[10  6  7 21 44]
10
7
44


In [6]:
# створити 2-мірний масив з цілих чисел з інтервалу 10-50
arr = np.random.randint(10, 50, (4,4))
print(arr)

[[24 40 40 45]
 [26 30 26 13]
 [46 19 11 29]
 [40 35 41 37]]


In [7]:
# отримати значення останнього елемента в 2 рядку
el = arr[1, -1]
print(el)

13


In [8]:
# отримати значення останнього рядка
vect = arr[-1]
print(vect)

[40 35 41 37]


In [9]:
# отримати `зріз` з 1 по 2 рядок
mat = arr[0:2]
print(mat)

[[24 40 40 45]
 [26 30 26 13]]


In [10]:
# вилучити 2 та 3 стовбчики `arr`
mat = arr[0:4, 1:3]
print(mat)

[[40 40]
 [30 26]
 [19 11]
 [35 41]]


In [11]:
# вилучити непарні рядки `arr`
mat = arr[0:4:2]
print(mat)

[[24 40 40 45]
 [46 19 11 29]]


In [12]:
# фільтрувати елементи масива за умовою
els = arr[arr > 20]
print(els)

[24 40 40 45 26 30 26 46 29 40 35 41 37]


### ЗАВДАННЯ 3

In [13]:
### ЗАВДАННЯ 3.1: створити масив 4х5 нормально розподілений випадкових чисел 3 інтервалу [10 - 100]
arr3_1 = np.random.randint(10, 100, (4,5))
print(arr3_1)

[[12 17 41 58 91]
 [16 60 28 38 35]
 [71 93 97 93 27]
 [57 56 72 59 38]]


In [18]:
### ЗАВДАННЯ 3.2:  вивести 3-елемент в 2-му рядку
el3_2 = arr3_1[1, -3]
print(el3_2)

28


In [21]:
### ЗАВДАННЯ 3.3:  вивести 2-й рядок масива `arr3_1`
vect3_3 = arr3_1[1]
print(vect3_3)

[16 60 28 38 35]


In [32]:
### ЗАВДАННЯ 3.4:  вивести 3 колонку масива `arr3_1`
vect3_4 = arr3_1[0:4, 2:3]
print(vect3_4)

[[41]
 [28]
 [97]
 [72]]


In [34]:
### ЗАВДАННЯ 3.5: вивести матрицю  з 2 та 3 рядка та 2 та 3 колонки масива `arr3_1`
mat3_5 = arr3_1[0:4, 1:3]
print(mat3_5)

[[17 41]
 [60 28]
 [93 97]
 [56 72]]


## 4. Матричні компоненти масива

### ПРИКЛАДИ

In [35]:
# створити одиничну матрицю розміру 3х3
mat = np.eye(3)
print(mat)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [36]:
# створити матрицю із заданою диагоналлю
mat = np.diag([1,2,3,4,5])
print(mat)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [3]:
# вилучити головну діагональ матриці `diag`
mat = np.random.rand(3,3)
print(mat, end="\n...\n")
print(np.diag(mat))

[[0.70047287 0.0115198  0.04582227]
 [0.77585935 0.84197712 0.66242519]
 [0.56751594 0.30518102 0.31726625]]
...
[0.70047287 0.84197712 0.31726625]


In [38]:
# транспонувати матрицю `mat` (https://ru.wikipedia.org/wiki/Транспонированная_матрица)
mT = np.transpose(mat)
print(mT)

[[0.10263009 0.38013428 0.13081808 0.92068994 0.56336745]
 [0.40544136 0.22218125 0.97246083 0.14134755 0.73776927]
 [0.18096252 0.19181494 0.06836243 0.02615896 0.97391199]
 [0.93661402 0.21267382 0.11863977 0.04600703 0.95916625]
 [0.39655511 0.46984039 0.79133217 0.20937635 0.61838008]]


In [39]:
# отримати детермінант матриці `det` (https://ru.wikipedia.org/wiki/Определитель)
print(np.linalg.det(mat))

-0.15297054080032466


In [40]:
# отримати зворотню матриці `det` (https://ru.wikipedia.org/wiki/Обратная_матрица)
invM = np.linalg.inv(mat)
print(invM)

[[-0.01181398 -0.40477017 -0.12608414  1.237291    0.05753295]
 [-0.00806114 -3.10534901  1.24249026  0.79781401  0.50446187]
 [-1.2665513   0.45670507 -0.39439087 -0.73765668  1.21967212]
 [ 1.35161836 -0.34915496 -0.38402652  0.14555185 -0.15933023]
 [-0.08136475  3.89594135 -0.1507037  -1.14306378 -0.71091842]]


### ЗАВАДАННЯ 4

In [46]:
# ЗАВДАННЯ 4.1: створити квадратну матрицю з 36 рівномірно розподілених цілих 
# елементів з інтервалу 100 - 200
mat4_1 = np.eye(6)
print(mat4_1)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [5]:
# ЗАВДАННЯ 4.2: вивести головну діагональ матниці `mat4_1`
mat4_1 = np.random.rand(6,6)
print(mat4_1, end="\n...\n")
print(mat4_1)

[[0.38615598 0.88037653 0.26074661 0.45752346 0.66530152 0.82665918]
 [0.86324153 0.24414565 0.93428505 0.21993352 0.91648345 0.80833718]
 [0.72865817 0.90704554 0.57475112 0.77922575 0.79542338 0.57409764]
 [0.25830845 0.6225794  0.33899988 0.16218679 0.88556072 0.73072934]
 [0.70993524 0.74520582 0.26235223 0.59929524 0.50588755 0.97658308]
 [0.99347512 0.5572148  0.84894207 0.12558145 0.45375885 0.87360294]]
...
[[0.38615598 0.88037653 0.26074661 0.45752346 0.66530152 0.82665918]
 [0.86324153 0.24414565 0.93428505 0.21993352 0.91648345 0.80833718]
 [0.72865817 0.90704554 0.57475112 0.77922575 0.79542338 0.57409764]
 [0.25830845 0.6225794  0.33899988 0.16218679 0.88556072 0.73072934]
 [0.70993524 0.74520582 0.26235223 0.59929524 0.50588755 0.97658308]
 [0.99347512 0.5572148  0.84894207 0.12558145 0.45375885 0.87360294]]


In [6]:
# ЗАВДАННЯ 4.3: транспонувати матрицю 'mat4_1'
trans4_3 = np.transpose(mat4_1)
print(trans4_3)

[[0.38615598 0.86324153 0.72865817 0.25830845 0.70993524 0.99347512]
 [0.88037653 0.24414565 0.90704554 0.6225794  0.74520582 0.5572148 ]
 [0.26074661 0.93428505 0.57475112 0.33899988 0.26235223 0.84894207]
 [0.45752346 0.21993352 0.77922575 0.16218679 0.59929524 0.12558145]
 [0.66530152 0.91648345 0.79542338 0.88556072 0.50588755 0.45375885]
 [0.82665918 0.80833718 0.57409764 0.73072934 0.97658308 0.87360294]]


In [7]:
# ЗАВДАННЯ 4.4: вирахувати зворотню до 'mat4_1' матрицю 
inv4_4 = np.linalg.inv(mat4_1)
print(inv4_4)

[[-10.80028851  -3.67496297   2.38969857   6.30593848   4.38850005
    1.86947331]
 [ -0.50798051  -2.05316786   0.93175432   1.33434182  -0.74169049
    1.48115387]
 [  9.7439655    3.61817306  -1.5421587   -6.59176141  -4.84717253
   -0.62251684]
 [  5.26967016   2.74911892  -0.46555709  -4.70039277  -1.0394471
   -2.13064721]
 [ -5.51534504  -1.18116579   1.33800086   4.39694103   1.75868896
   -0.21123098]
 [  5.24457228   2.19109446  -2.4413315   -3.22475245  -0.57131381
   -0.90509957]]


## 5. Операції над масивами

### ПРИКЛАДИ

In [11]:
# задати вектор з 10 елементів
vect = np.array([1, 3, 2, -3, 5, 0, 8, 4, -2, 10])
print(vect)

[ 1  3  2 -3  5  0  8  4 -2 10]


In [14]:
# вирахувати суму елеметнів
s = np.sum(vect)
print(s)

# знайти мінімальний ел-т
m = np.min(vect)
print(m)

# відсортувати вектор по зростанню
vs = np.sort(vect)
print(vs)

# знайти середнє значення
mid = np.average(vect)
print(mid)

28
-3
[-3 -2  0  1  2  3  4  5  8 10]
2.8


In [15]:
# матриця 3х3 сконструйована різними методами
mat = np.array([np.arange(1,4), [-2, 4, 6], np.full(3,77)])
print(mat)

[[ 1  2  3]
 [-2  4  6]
 [77 77 77]]


In [16]:
# сума по колонкам `axis=0`
s = np.sum(mat, axis=0)
print(s)

[76 83 86]


In [17]:
# мінімум по рядкам
m = np.min(mat, axis=1)
print(m)

[ 1 -2 77]


In [18]:
# збільшити ел-ти масива вдвічі
v2 = mat * 2
print(v2)

[[  2   4   6]
 [ -4   8  12]
 [154 154 154]]


In [19]:
M = np.array([[1,2,3],[4,-3,6],[7,8,0]])
N = np.array([[1,1,1],[2,2,2],[3,3,3]])
print(M, N, sep="\n")

[[ 1  2  3]
 [ 4 -3  6]
 [ 7  8  0]]
[[1 1 1]
 [2 2 2]
 [3 3 3]]


In [20]:
# перемножити елементи матриць M, N
K = M * N
print(K)
# або ->
K = np.multiply(N, M)
print(K)

[[ 1  2  3]
 [ 8 -6 12]
 [21 24  0]]
[[ 1  2  3]
 [ 8 -6 12]
 [21 24  0]]


In [21]:
# поелементний поділ
K = N / M
print(K)

[[ 1.          0.5         0.33333333]
 [ 0.5        -0.66666667  0.33333333]
 [ 0.42857143  0.375              inf]]


c:\users\zver\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in true_divide
  


In [22]:
# скалярне множення матриць (https://ru.wikipedia.org/wiki/Умножение_матриц)
prod = np.dot(N, M)
print(prod)

[[12  7  9]
 [24 14 18]
 [36 21 27]]


In [23]:
# возвести матрицю `prod` в ступінь 3
pmat = np.linalg.matrix_power(prod, 3)
print(pmat)

[[ 33708  19663  25281]
 [ 67416  39326  50562]
 [101124  58989  75843]]


In [24]:
# додати елементи до 1-вимірного масива
mat = np.array([1,2,3])
mat = np.append(mat, [5,6,7,8])
print(mat)

[1 2 3 5 6 7 8]


In [25]:
# вставити елемент `4` в масив після 3-го елемента
mat = np.insert(mat, 3, 4)
print(mat)

[1 2 3 4 5 6 7 8]


In [26]:
# видалити елемент з індексом 6
mat = np.delete(mat, 6)
print(mat)

[1 2 3 4 5 6 8]


In [27]:
#  копіювання та присвоювання масивів
M = np.random.randint(1, 10, 5 )
print(M)

# присвоїти масив `M` в `N`
N = M
print(N)
print(id(M), id(N))

# копіювати масив `M` в `K`
K = np.copy(M)
print(K)
print(id(M), id(K))

[5 6 2 1 6]
[5 6 2 1 6]
2189991281552 2189991281552
[5 6 2 1 6]
2189991281552 2189940223024


In [28]:
# конкатенація масивів по рядкам
arr1 = np.array([[1,2,3,4], [1,2,3,4]])
arr2 = np.array([[5,6,7,8], [5,6,7,8]])
arr3 = np.concatenate((arr1, arr2), axis=0)
print(arr3)
# по колонкам `axis = 1`
arr4 = np.concatenate((arr1, arr2), axis=1)
print(arr4)

[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]]
[[1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]]


### ЗАВДАННЯ 5

In [29]:
# ЗАВДАННЯ 5.1: просумувати по рядкам масив випадкових чисел розмірностю 3х4
mat5_1 = np.random.rand(3, 4)
sum_mat5_1 = np.sum(mat5_1)
print(sum_mat5_1)

6.432860809554864


In [30]:
# ЗАВДАННЯ 5.2: знайти мінімальний елемент матриці `sum_mat5_1`
min_mat5_1 = np.min(mat5_1)
print(min_mat5_1)

0.07292706699909302


In [34]:
# ЗАВДАННЯ 5.3: створити масив додавши до елементів `mat5_1`  число 100
mat5_3 = np.array([1,2,3])
mat = np.append(mat5_3, [100])
print(mat)

[  1   2   3 100]


In [35]:
# ЗАВДАННЯ 5.4: помножити матрицю `mat5_1` на головну діагональ матриці `mat5_3`
mat5_4 = np.dot(mat5_1, mat5_3)
print(mat5_4)

ValueError: shapes (3,4) and (3,) not aligned: 4 (dim 1) != 3 (dim 0)

In [36]:
# ЗАВДАННЯ 5.5: додати справа до матриці `mat5_3` матрицю `mat5_4` 
# вивести ранг отриманої матриці
mat5_5 = np.append(mat5_3, mat5_4)
r = np.linalg.matrix_rank(mat5_5)
print(r)

NameError: name 'mat5_4' is not defined